services:
  stepstothefuture_be:
    container_name: stepstothefuture_be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - APP_PORT=8080
    volumes:
      - /backend/backend/static/images:/app/static/images
