services:
  stepstothefuture_be:
    container_name: stepstothefuture_be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

volumes:
  postgres-data:
  redis-data:

networks:
  my-network:
    driver: bridge